import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "../styles/Home.module.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <nav>
          <img />
          <Link href="/">Home</Link>
          <Link href="/events">Events</Link>
          <Link href="/about-us">About Us</Link>
        </nav>
      </header>

      <main className={styles.main}>
        {data.map((data) => {
          return (
            <Link key={data.id} href={`/events/${data.id}`}>
              <Image
                width={400}
                height={200}
                alt={data.title}
                src={data.image}
              />
              <h2>{`${data.title}`}</h2>
              <p>{data.description}</p>
            </Link>
          );
        })}
      </main>
      <footer>
        <p> 2022 Time to Code - A NextJS project</p>
      </footer>
    </>
  );
}

export async function getServerSideProps() {
  const { events_categories } = await import("../data/data.json");
  return {
    props: {
      data: events_categories,
    },
  };
}
